### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by chinoll** [answerdev/answer#91]
**Describe the bug**
docker启动失败，在一个未知IP上监听了53端口
**To Reproduce**
```
[config-file] try to install...
[config-file] /data/conf/config.yaml already exists
[upload-dir] try to install...
[upload-dir] install success, upload directory is /data/upfiles
[i18n] try to install i18n bundle...
[i18n] find i18n bundle 3
[i18n] install en_US.yaml bundle...
[i18n] install en_US.yaml bundle success
[i18n] install it_IT.yaml bundle...
[i18n] install it_IT.yaml bundle success
[i18n] install zh_CN.yaml bundle...
[i18n] install zh_CN.yaml bundle success
install all initial environment done
read config successfully
new database failed:  dial tcp: lookup db on IP:53: no such host
init database error:  dial tcp: lookup db on ip:53: no such host
panic: dial tcp: lookup db on IP:53: no such host

goroutine 1 [running]:
main.runApp()
        /go/src/github.com/answerdev/answer/cmd/answer/main.go:51 +0x22c
main.glob..func1(0x3433a20?, {0xef2e49?, 0x2?, 0x2?})
        /go/src/github.com/answerdev/answer/cmd/answer/command.go:52 +0x17
github.com/spf13/cobra.(*Command).execute(0x3433a20, {0xc0005dcf20, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x3432da0)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.Execute()
        /go/src/github.com/answerdev/answer/cmd/answer/command.go:155 +0x25
main.main()
        /go/src/github.com/answerdev/answer/cmd/answer/main.go:37 +0x17
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chinoll** [comment]
> 

映射的目录下并没有创建任何文件

**Comment by chinoll** [comment]
> According to the error message: `new database failed: dial tcp: lookup db on IP:53: no such host`
> 
> Please check your configuration file: in the configuration file
> 
> ```yaml
> data:
>   database:
>     driver: "mysql"
>     connection: "db:3306" 
> ```
> 
> The default database connection here in older version should be like this `db:3306`, you can modify it according to your actual mysql situation, e.g. `root:root@tcp(127.0.0.1:3306)/answer`
> 
> We recommend to modify the configuration file manually. The configuration file is in `/data/conf/config.yaml`, just restart it after modification.
> 
> 根据错误信息提示：`new database failed: dial tcp: lookup db on IP:53: no such host`
> 
> 请查看您的配置文件：配置文件中
> 
> ```yaml
> data:
>   database:
>     driver: "mysql"
>     connection: "db:3306" 
> ```
> 
> 在旧版本中这里的连接默认应该是这样的 `db:3306`，您可以根据您的实际mysql情况进行修改，如：`root:root@tcp(127.0.0.1:3306)/answer`
> 
> 建议手动修改配置文件，配置文件目录在 `/data/conf/config.yaml`，修改后重新启动即可。
> 
> 如果还出现其他问题，请提供启动的方式和命令，方便我们跟进排查解决~

映射的目录下并没有创建任何文件

**Comment by chinoll** [comment]
还有，INSTALL.md中写了以二进制文件的方式启动，但是在releases下并未找到二进制文件

**Comment by chinoll** [comment]
> > > 请提供启动的方式和命令，如果是以 `docker run -d -p 9080:80 -v answer-data:/data --name answer answerdev/answer:latest` 命令启动的话，是挂载在docker 对应的 volume 目录下（非当前目录）。如果是以其他命令启动，请提供。
> > 
> > 
> > 使用repo提供的docker-compose.yaml启动
> 
> 如果是以 旧版本的 docker-compose 启动的话，也是放在 对应的 volume 下，你可以提供docker-compose供参考。

最新的repo提供的docker-compose，只修改了80映射的端口号，看INSTALL.md里介绍的，新版可以使用sqlite作为数据库，该如何修改成sqlite

**Comment by chinoll** [comment]
> > > > > 请提供启动的方式和命令，如果是以 `docker run -d -p 9080:80 -v answer-data:/data --name answer answerdev/answer:latest` 命令启动的话，是挂载在docker 对应的 volume 目录下（非当前目录）。如果是以其他命令启动，请提供。
> > > > 
> > > > 
> > > > 使用repo提供的docker-compose.yaml启动
> > > 
> > > 
> > > 如果是以 旧版本的 docker-compose 启动的话，也是放在 对应的 volume 下，你可以提供docker-compose供参考。
> > 
> > 
> > 最新的repo提供的docker-compose，只修改了80映射的端口号，看INSTALL.md里介绍的，新版可以使用sqlite作为数据库，该如何修改成sqlite
> 
> 如果是新版本，并且想使用 sqlite，建议直接使用命令 `docker run -d -p 9080:80 -v answer-data:/data --name answer answerdev/answer:latest` 直接启动然后进入安装链接进行安装。
> 
> 如果使用docker-compose也可以参考安装文档中的方式进行安装 [`main`/INSTALL_CN.md](https://github.com/answerdev/answer/blob/main/INSTALL_CN.md?rgh-link-date=2022-11-21T15%3A32%3A37Z)
> 
> 也可以手动修改配置文件中的连接
> 
> ```yaml
> data:
>   database:
>     driver: "sqlite3"
>     connection: "sqlite db path"
> ```

用这两种方式启动均会报开头的错误，即使没有做任何的修改

**Comment by chinoll** [comment]
无法进入引导页面

**Comment by chinoll** [comment]
> 使用 `docker volume -l` 查看当前是否存在之前旧版本的 answer-data 的 volume，如果有将它删除后再重新启动。`docker volume rm answer-data`

全部删了也一样报这些错误

**Comment by chinoll** [comment]
> 使用 `docker volume -l` 查看当前是否存在之前旧版本的 answer-data 的 volume，如果有将它删除后再重新启动。`docker volume rm answer-data`

问题似乎解决了，手动指定0.4.0就可以启动，使用latest就会启动失败，应该是镜像缓存问题

**Comment by chinoll** [comment]
> > 
> 
> 不用的，只要您使用的新旧版本前后数据库一致就不需要 install

好的，谢谢
